### ISSUE TITLE
Missing --first flag for first node needs better error message. [Good first issue]

### ISSUE THREAD

**Issue by Folaht** [maidsafe/sn_node#1314]
**Is your feature request related to a problem? Please describe.**
https://forum.safedev.org/t/latest-sn-node-versions-not-working-routing-network-emptyboostrapnodeslist/2973

**Describe the solution you'd like**
A clear message that `--first` is missing.

**Comment by clD11** [comment]
@bochaco @Folaht Has this been picked up or resolved? If not I would be keen to pick it up and work on a PR

**Comment by Folaht** [comment]
It currently is even more vague.

```
$ ~/.safe/node/sn_node --local-addr '127.0.0.1:12000'
Warning: Local Address provided is skipped since external address is not provided.
Cannot start node due to error: Routing(Network(UnspecifiedLocalIp))
[sn_node] ERROR 2021-04-12T04:37:01.216113047+02:00 [src/bin/sn_node.rs:110] Cannot start node due to error: Routing(Network(UnspecifiedLocalIp))
```

**Comment by clD11** [comment]
@Folaht @bochaco okay, I will pick this up and look to improve the args handling and error messages

**Comment by bochaco** [comment]
It's find with me, I think it'll be good to get help from @lionel1704 to review it when it's ready as he's been working on such type of improvments in qp2p.

**Comment by clD11** [comment]
@bochaco it is a good question where this message is best handled. I saw @lionel1704 changes in the `config_handler` to deal with other params which are passed in but this param is slightly more tricky :smile:  

The `sns_routing` and `qp2p` use the `qp2p::Config` which dosent have a notion of `--first` so at that point I guess it is just an `UnspecifiedLocalIp` in the `sns_node` it has a notion of `--first` so possibly improving the message there where it is as close to its use might make sense. I will raise a PR for thoughts
