### ISSUE TITLE
Cannot Create Account

### ISSUE THREAD

**Issue by Heteroculturalism** [maidsafe/sn_node#934]
I installed 0.0.5 on Windows 10, but when I attempt to create an account, I get a request timeout error (see image).  Please advise.

![image](https://user-images.githubusercontent.com/2056672/73876501-b7e8e880-481c-11ea-8a9c-71f8b5f6d909.png)

**Comment by frabrunelle** [comment]
Are you running a local vault or trying to connect to the Shared Vault network?

I recommend following the instructions in [this forum post](https://safenetforum.org/t/new-release-vault-phase-1-real-vault/29712).

**Comment by Heteroculturalism** [comment]
I was running neither.  If this is a requirement, I think it should be stated explicitly in the app installation workflow.  This is the starting point for the Safe app experience, after all.

**Comment by frabrunelle** [comment]
Yes, it's planned for the SAFE Network App to run a vault on your behalf eventually. See [this video](https://www.youtube.com/watch?v=1gMBbR03RVo) 🙂 

For now you need to either run a vault locally and connect to the shared vault by setting up a config file (you can do this using the SAFE CLI as shown in the post I linked above).
